<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_mitra</name>
   <tag></tag>
   <elementGuidId>d9dee92e-60d5-4e57-8bb6-91aaaf6155c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;aside&quot;]/ng-scrollbar/div/div/div/div/div/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;aside&quot;]/ng-scrollbar/div/div/div/div/div/ul/li[2]/a/span</value>
      <webElementGuid>db0b555d-7531-4a17-896a-07d09ed20206</webElementGuid>
   </webElementProperties>
</WebElementEntity>
